import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sample Next JS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='py-5 w-full bg-[#00e5ff] min-h-[80vh] px-4'>
        <div className='w-full md:grid md:grid-flow-row md:grid-cols-3'>
            <Link href={'/countries'} className='md:w-[240px] flex justify-center items-center mx-auto mt-4 md:mt-11 border-4 rounded-3xl border-double h-[200px] text-4xl font-extrabold text-white bg-[#00e5ff] hover:underline'>
              <div>Countries</div>
            </Link>
            <Link href={'/users'} className='md:w-[240px] flex justify-center items-center mx-auto mt-4 md:mt-11 border-4 rounded-3xl border-double h-[200px] text-4xl font-extrabold text-white bg-[#00e5ff] hover:underline'>
              <div>Users</div>
            </Link>
            <Link href={'/dashboard'} className='md:w-[240px] flex justify-center items-center mx-auto mt-4 md:mt-11 border-4 rounded-3xl border-double h-[200px] text-4xl font-extrabold text-white bg-[#00e5ff] hover:underline'>
              <div>Dashboard</div>
            </Link>
        </div>
      </div>
    </>
  )
}

// Go to http://localhost:3000 to check/validate changes made in this file.
